name: Publish Docker Image

on:
  push:
    branches:
      - main  
jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKER_HUB }}
      run: |
        echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 -t opsifygit/flask_app:latest .
        docker push opsifygit/flask_app:latest
