name: Publish Docker Image

on:
  push:
    branches:
      - main  
jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Docker login
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    - name: Build
      run: |
        docker build . --file Dockerfile --tag opsifygit/flask_app:latest
    - name: Publish
      run: |
        docker push opsifygit/flask_app:latest
